### ISSUE TITLE
Test for Virtualbox 6.0 (or 6.1) compatibility

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#96]
Oracle did not kill Virtualbox and look and behold a version 6.0 has been released. Our project and Vagrantfile should be tested for Virtualbox 6.0 compatibility, with at least updates in documentation (https://seravo.com/docs/development/how-to-install/#windows-cygwin) and perhaps also some tweaks in the Vagrantfile.

**Comment by l3ku** [comment]
I have been using Virtualbox 6.x.x on OS X since almost immediately after it was released, and there have been no issues due to Virtualbox with our Vagrant box. We should also probably look into testing on Windows with Virtualbox 6.

**Comment by l3ku** [comment]
There is however this warning when starting the vagrant environment:
```
  wordpress-box: The guest additions on this VM do not match the installed version of
    wordpress-box: VirtualBox! In most cases this is fine, but in rare cases it can
    wordpress-box: prevent things such as shared folders from working properly. If you see
    wordpress-box: shared folder errors, please make sure the guest additions within the
    wordpress-box: virtual machine match the version of VirtualBox you have installed on
    wordpress-box: your host and reload your VM.
    wordpress-box:
    wordpress-box: Guest Additions Version: 5.2.18
    wordpress-box: VirtualBox Version: 6.0
```
This could cause some problems.
